# Generated by Django 4.1 on 2023-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['-total_likes'], name='images_imag_total_l_632299_idx'),
        ),
    ]
